[workspace]
resolver = "2"
members = ["mimizu", "mimizu_vr"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
overflow-checks = false
debug = false

[profile.release]
codegen-units = 1
lto = true
strip = true
